import { Category } from '@/lib/types'

export const categories: Category[] = [
  {
    id: 'marketing',
    name: 'Marketing & Advertising',
    icon: '📢',
    questions: [
      {
        id: 'mkt-1',
        type: 'multi-select',
        text: 'How do you currently generate leads?',
        isScored: true,
        options: [
          { value: 'referrals', label: 'Referrals only', score: 1 },
          { value: 'paid-ads', label: 'Paid Ads (Google/Meta)', score: 3 },
          { value: 'seo', label: 'SEO / Organic content', score: 3 },
          { value: 'social', label: 'Social media', score: 2 },
          { value: 'events', label: 'Events / Networking', score: 2 },
          { value: 'ai-tools', label: 'AI tools / Automated outbound', score: 5 },
        ],
      },
      {
        id: 'mkt-2',
        type: 'select',
        text: 'How automated is your marketing campaign management?',
        isScored: true,
        options: [
          { value: '1', label: '100% manual — everything done by hand', score: 1 },
          { value: '2', label: 'Somewhat automated — basic scheduling', score: 2 },
          { value: '3', label: 'Partially — some automated rules active', score: 3 },
          { value: '4', label: 'Mostly automated — connected workflows', score: 4 },
          { value: '5', label: 'Fully automated — AI optimizes in real-time', score: 5 },
        ],
      },
      {
        id: 'mkt-3',
        type: 'select',
        text: 'Do you use AI for any marketing tasks?',
        isScored: true,
        options: [
          { value: 'none', label: 'No, no AI at all', score: 0 },
          { value: 'experimenting', label: 'Experimenting — ChatGPT for basic content', score: 2 },
          { value: 'some', label: 'Some tasks — copywriting, analysis, segmentation', score: 3 },
          { value: 'core', label: 'Core part of workflow — AI automations integrated', score: 5 },
        ],
      },
      {
        id: 'mkt-4',
        type: 'textarea',
        text: 'What is your biggest marketing challenge right now?',
        isScored: false,
        placeholder: 'E.g., We don\'t have a consistent content creation process...',
      },
    ],
  },
  {
    id: 'sales',
    name: 'Sales & CRM',
    icon: '💼',
    questions: [
      {
        id: 'sales-1',
        type: 'select',
        text: 'How do you track your sales pipeline?',
        isScored: true,
        options: [
          { value: 'nothing', label: 'Spreadsheets or nothing formal', score: 1 },
          { value: 'basic-crm', label: 'Basic CRM (HubSpot free, Pipedrive)', score: 2 },
          { value: 'advanced-crm', label: 'Advanced CRM with automations', score: 4 },
          { value: 'ai-crm', label: 'CRM with AI — scoring, insights, predictions', score: 5 },
        ],
      },
      {
        id: 'sales-2',
        type: 'select',
        text: 'What is your average response time to a new lead?',
        isScored: true,
        options: [
          { value: '24h+', label: 'More than 24 hours', score: 1 },
          { value: 'same-day', label: 'Same day', score: 2 },
          { value: '2h', label: 'Less than 2 hours', score: 3 },
          { value: '15min', label: 'Less than 15 minutes — automated response', score: 5 },
        ],
      },
      {
        id: 'sales-3',
        type: 'select',
        text: 'How do you qualify leads?',
        isScored: true,
        options: [
          { value: 'gut', label: 'Gut feeling / Intuition', score: 1 },
          { value: 'basic', label: 'Basic manual criteria', score: 2 },
          { value: 'scoring', label: 'Defined scoring system', score: 4 },
          { value: 'ai-scoring', label: 'AI-assisted scoring', score: 5 },
        ],
      },
      {
        id: 'sales-4',
        type: 'textarea',
        text: 'What is the slowest or most tedious part of your sales process?',
        isScored: false,
        placeholder: 'E.g., Manual follow-ups, proposals take days to create...',
      },
    ],
  },
  {
    id: 'operations',
    name: 'Operations & Workflows',
    icon: '⚙️',
    questions: [
      {
        id: 'ops-1',
        type: 'select',
        text: 'How many hours per week does your team spend on repetitive manual tasks?',
        isScored: true,
        options: [
          { value: '<5', label: 'Less than 5 hours', score: 5 },
          { value: '5-15', label: '5-15 hours', score: 3 },
          { value: '15-30', label: '15-30 hours', score: 2 },
          { value: '30+', label: 'More than 30 hours', score: 1 },
        ],
      },
      {
        id: 'ops-2',
        type: 'select',
        text: 'Do you use workflow automation tools (Zapier, n8n, Make, etc.)?',
        isScored: true,
        options: [
          { value: 'none', label: 'None', score: 0 },
          { value: 'basic', label: 'A few basic automations', score: 2 },
          { value: 'multiple', label: 'Multiple automated workflows', score: 4 },
          { value: 'integrated', label: 'Fully integrated — AI + automation', score: 5 },
        ],
      },
      {
        id: 'ops-3',
        type: 'select',
        text: 'How documented are your business processes?',
        isScored: true,
        options: [
          { value: 'none', label: 'Not documented', score: 0 },
          { value: 'some', label: 'Some basic SOPs', score: 2 },
          { value: 'documented', label: 'Well documented and updated', score: 4 },
          { value: 'living', label: 'Living documentation + connected automation', score: 5 },
        ],
      },
      {
        id: 'ops-4',
        type: 'textarea',
        text: 'What process in your business would you most want to automate?',
        isScored: false,
        placeholder: 'E.g., New client onboarding, report generation...',
      },
    ],
  },
  {
    id: 'customerExperience',
    name: 'Customer Experience',
    icon: '🤝',
    questions: [
      {
        id: 'cx-1',
        type: 'select',
        text: 'How do you handle customer support inquiries?',
        isScored: true,
        options: [
          { value: 'manual', label: 'Manual email / WhatsApp without structure', score: 1 },
          { value: 'shared', label: 'Shared inbox / basic tool', score: 2 },
          { value: 'helpdesk', label: 'Dedicated helpdesk (Zendesk, Freshdesk)', score: 3 },
          { value: 'ai-bot', label: 'AI chatbot + human escalation', score: 5 },
        ],
      },
      {
        id: 'cx-2',
        type: 'select',
        text: 'How personalized is your customer communication?',
        isScored: true,
        options: [
          { value: 'generic', label: 'One-size-fits-all', score: 1 },
          { value: 'basic-seg', label: 'Basic segmentation (by type)', score: 2 },
          { value: 'personalized', label: 'Personalized by behavior/history', score: 4 },
          { value: 'ai-driven', label: 'AI-driven real-time personalization', score: 5 },
        ],
      },
      {
        id: 'cx-3',
        type: 'select',
        text: 'Do you collect and act on customer feedback systematically?',
        isScored: true,
        options: [
          { value: 'rarely', label: 'Rarely', score: 1 },
          { value: 'manual', label: 'Sometimes — manual review', score: 2 },
          { value: 'regular', label: 'Regular surveys with analysis', score: 3 },
          { value: 'automated', label: 'Automated feedback loops + AI analysis', score: 5 },
        ],
      },
      {
        id: 'cx-4',
        type: 'textarea',
        text: 'How would your customers describe their experience with your business?',
        isScored: false,
        placeholder: 'E.g., Good service but slow responses, we lack follow-up...',
      },
    ],
  },
  {
    id: 'dataAnalytics',
    name: 'Data & Analytics',
    icon: '📊',
    questions: [
      {
        id: 'data-1',
        type: 'select',
        text: 'How do you make business decisions?',
        isScored: true,
        options: [
          { value: 'gut', label: 'Experience and intuition', score: 1 },
          { value: 'basic', label: 'Basic metrics (revenue, expenses)', score: 2 },
          { value: 'dashboards', label: 'Dashboards with real-time data', score: 4 },
          { value: 'ai', label: 'AI-assisted insights + predictions', score: 5 },
        ],
      },
      {
        id: 'data-2',
        type: 'select',
        text: 'Are your data sources (CRM, ads, finance, ops) connected?',
        isScored: true,
        options: [
          { value: 'siloed', label: 'Completely siloed', score: 1 },
          { value: 'some', label: 'Some connections', score: 2 },
          { value: 'mostly', label: 'Mostly connected', score: 4 },
          { value: 'unified', label: 'Unified data layer', score: 5 },
        ],
      },
      {
        id: 'data-3',
        type: 'select',
        text: 'How often do you review performance data?',
        isScored: true,
        options: [
          { value: 'rarely', label: 'Rarely', score: 1 },
          { value: 'monthly', label: 'Monthly', score: 2 },
          { value: 'weekly', label: 'Weekly', score: 4 },
          { value: 'realtime', label: 'Real-time — dashboards + alerts', score: 5 },
        ],
      },
      {
        id: 'data-4',
        type: 'textarea',
        text: 'What data do you wish you had that you currently don\'t?',
        isScored: false,
        placeholder: 'E.g., We don\'t know the true ROI per channel, no visibility into customer lifetime value...',
      },
    ],
  },
]
