import { Category } from '@/lib/types'

export const categories: Category[] = [
  {
    id: 'marketing',
    name: 'Marketing y Publicidad',
    icon: '📢',
    questions: [
      {
        id: 'mkt-1',
        type: 'multi-select',
        text: '¿Cómo generas leads actualmente?',
        isScored: true,
        options: [
          { value: 'referrals', label: 'Solo referidos', score: 1 },
          { value: 'paid-ads', label: 'Paid Ads (Google/Meta)', score: 3 },
          { value: 'seo', label: 'SEO / Contenido orgánico', score: 3 },
          { value: 'social', label: 'Redes sociales', score: 2 },
          { value: 'events', label: 'Eventos / Networking', score: 2 },
          { value: 'ai-tools', label: 'Herramientas de AI / Outbound automatizado', score: 5 },
        ],
      },
      {
        id: 'mkt-2',
        type: 'select',
        text: '¿Qué tan automatizada está la gestión de tus campañas de marketing?',
        isScored: true,
        options: [
          { value: '1', label: '100% manual — todo se hace a mano', score: 1 },
          { value: '2', label: 'Algo automatizado — usamos scheduling básico', score: 2 },
          { value: '3', label: 'Parcialmente — algunas reglas automáticas activas', score: 3 },
          { value: '4', label: 'Mayormente automatizado — workflows conectados', score: 4 },
          { value: '5', label: 'Totalmente automatizado — AI optimiza en tiempo real', score: 5 },
        ],
      },
      {
        id: 'mkt-3',
        type: 'select',
        text: '¿Usas AI para alguna tarea de marketing?',
        isScored: true,
        options: [
          { value: 'none', label: 'No, nada de AI', score: 0 },
          { value: 'experimenting', label: 'Experimentando — ChatGPT para contenido básico', score: 2 },
          { value: 'some', label: 'Algunas tareas — copywriting, análisis, segmentación', score: 3 },
          { value: 'core', label: 'Parte central del workflow — automatizaciones con AI integradas', score: 5 },
        ],
      },
      {
        id: 'mkt-4',
        type: 'textarea',
        text: '¿Cuál es tu mayor reto de marketing en este momento?',
        isScored: false,
        placeholder: 'Ej: No tenemos un proceso consistente para generar contenido...',
      },
    ],
  },
  {
    id: 'sales',
    name: 'Ventas y CRM',
    icon: '💼',
    questions: [
      {
        id: 'sales-1',
        type: 'select',
        text: '¿Cómo rastrean su pipeline de ventas?',
        isScored: true,
        options: [
          { value: 'nothing', label: 'Hojas de cálculo o nada formal', score: 1 },
          { value: 'basic-crm', label: 'CRM básico (HubSpot free, Pipedrive)', score: 2 },
          { value: 'advanced-crm', label: 'CRM avanzado con automatizaciones', score: 4 },
          { value: 'ai-crm', label: 'CRM con AI — scoring, insights, predicciones', score: 5 },
        ],
      },
      {
        id: 'sales-2',
        type: 'select',
        text: '¿Cuál es tu tiempo promedio de respuesta a un nuevo lead?',
        isScored: true,
        options: [
          { value: '24h+', label: 'Más de 24 horas', score: 1 },
          { value: 'same-day', label: 'El mismo día', score: 2 },
          { value: '2h', label: 'Menos de 2 horas', score: 3 },
          { value: '15min', label: 'Menos de 15 minutos — respuesta automatizada', score: 5 },
        ],
      },
      {
        id: 'sales-3',
        type: 'select',
        text: '¿Cómo califican a sus leads?',
        isScored: true,
        options: [
          { value: 'gut', label: 'Intuición / Feeling', score: 1 },
          { value: 'basic', label: 'Criterios básicos manuales', score: 2 },
          { value: 'scoring', label: 'Sistema de scoring definido', score: 4 },
          { value: 'ai-scoring', label: 'Scoring asistido por AI', score: 5 },
        ],
      },
      {
        id: 'sales-4',
        type: 'textarea',
        text: '¿Cuál es la parte más lenta o tediosa de tu proceso de ventas?',
        isScored: false,
        placeholder: 'Ej: Follow-ups manuales, propuestas que tardan días en hacerse...',
      },
    ],
  },
  {
    id: 'operations',
    name: 'Operaciones y Workflows',
    icon: '⚙️',
    questions: [
      {
        id: 'ops-1',
        type: 'select',
        text: '¿Cuántas horas a la semana invierte tu equipo en tareas manuales repetitivas?',
        isScored: true,
        options: [
          { value: '<5', label: 'Menos de 5 horas', score: 5 },
          { value: '5-15', label: '5-15 horas', score: 3 },
          { value: '15-30', label: '15-30 horas', score: 2 },
          { value: '30+', label: 'Más de 30 horas', score: 1 },
        ],
      },
      {
        id: 'ops-2',
        type: 'select',
        text: '¿Usan herramientas de automatización (Zapier, n8n, Make, etc.)?',
        isScored: true,
        options: [
          { value: 'none', label: 'Ninguna', score: 0 },
          { value: 'basic', label: 'Algunas automatizaciones básicas', score: 2 },
          { value: 'multiple', label: 'Múltiples workflows automatizados', score: 4 },
          { value: 'integrated', label: 'Completamente integrado — AI + automatización', score: 5 },
        ],
      },
      {
        id: 'ops-3',
        type: 'select',
        text: '¿Qué tan documentados están tus procesos de negocio?',
        isScored: true,
        options: [
          { value: 'none', label: 'No están documentados', score: 0 },
          { value: 'some', label: 'Algunos SOPs básicos', score: 2 },
          { value: 'documented', label: 'Bien documentados y actualizados', score: 4 },
          { value: 'living', label: 'Documentación viva + automatización conectada', score: 5 },
        ],
      },
      {
        id: 'ops-4',
        type: 'textarea',
        text: '¿Qué proceso de tu negocio te gustaría más automatizar?',
        isScored: false,
        placeholder: 'Ej: El onboarding de clientes nuevos, la generación de reportes...',
      },
    ],
  },
  {
    id: 'customerExperience',
    name: 'Experiencia del Cliente',
    icon: '🤝',
    questions: [
      {
        id: 'cx-1',
        type: 'select',
        text: '¿Cómo manejan las consultas de soporte/servicio al cliente?',
        isScored: true,
        options: [
          { value: 'manual', label: 'Email manual / WhatsApp sin estructura', score: 1 },
          { value: 'shared', label: 'Bandeja compartida / herramienta básica', score: 2 },
          { value: 'helpdesk', label: 'Helpdesk dedicado (Zendesk, Freshdesk)', score: 3 },
          { value: 'ai-bot', label: 'Chatbot AI + escalación a humano', score: 5 },
        ],
      },
      {
        id: 'cx-2',
        type: 'select',
        text: '¿Qué tan personalizada es tu comunicación con clientes?',
        isScored: true,
        options: [
          { value: 'generic', label: 'Igual para todos', score: 1 },
          { value: 'basic-seg', label: 'Segmentación básica (por tipo)', score: 2 },
          { value: 'personalized', label: 'Personalizada por comportamiento/historial', score: 4 },
          { value: 'ai-driven', label: 'Personalización impulsada por AI en tiempo real', score: 5 },
        ],
      },
      {
        id: 'cx-3',
        type: 'select',
        text: '¿Recolectan y actúan sobre feedback de clientes de forma sistemática?',
        isScored: true,
        options: [
          { value: 'rarely', label: 'Rara vez', score: 1 },
          { value: 'manual', label: 'A veces — revisión manual', score: 2 },
          { value: 'regular', label: 'Encuestas regulares con análisis', score: 3 },
          { value: 'automated', label: 'Loops automatizados de feedback + análisis AI', score: 5 },
        ],
      },
      {
        id: 'cx-4',
        type: 'textarea',
        text: '¿Cómo describirían tus clientes su experiencia con tu empresa?',
        isScored: false,
        placeholder: 'Ej: Buen servicio pero lento en respuestas, nos falta seguimiento...',
      },
    ],
  },
  {
    id: 'dataAnalytics',
    name: 'Datos y Analítica',
    icon: '📊',
    questions: [
      {
        id: 'data-1',
        type: 'select',
        text: '¿Cómo toman decisiones de negocio?',
        isScored: true,
        options: [
          { value: 'gut', label: 'Experiencia e intuición', score: 1 },
          { value: 'basic', label: 'Métricas básicas (revenue, gastos)', score: 2 },
          { value: 'dashboards', label: 'Dashboards con datos en tiempo real', score: 4 },
          { value: 'ai', label: 'Insights asistidos por AI + predicciones', score: 5 },
        ],
      },
      {
        id: 'data-2',
        type: 'select',
        text: '¿Tus fuentes de datos (CRM, ads, finanzas, ops) están conectadas?',
        isScored: true,
        options: [
          { value: 'siloed', label: 'Completamente separadas', score: 1 },
          { value: 'some', label: 'Algunas conexiones', score: 2 },
          { value: 'mostly', label: 'Mayormente conectadas', score: 4 },
          { value: 'unified', label: 'Capa de datos unificada', score: 5 },
        ],
      },
      {
        id: 'data-3',
        type: 'select',
        text: '¿Con qué frecuencia revisan datos de rendimiento?',
        isScored: true,
        options: [
          { value: 'rarely', label: 'Rara vez', score: 1 },
          { value: 'monthly', label: 'Mensualmente', score: 2 },
          { value: 'weekly', label: 'Semanalmente', score: 4 },
          { value: 'realtime', label: 'En tiempo real — dashboards + alertas', score: 5 },
        ],
      },
      {
        id: 'data-4',
        type: 'textarea',
        text: '¿Qué datos te gustaría tener que hoy no tienes?',
        isScored: false,
        placeholder: 'Ej: No sabemos el verdadero ROI por canal, no tenemos visibilidad de customer lifetime value...',
      },
    ],
  },
]
